---
- name: Create directory
  ansible.builtin.file:
    path: '{{tmp_dir}}'
    state: directory
    mode: 0755

- name: Create file from template
  ansible.builtin.template:
    src: temp.j2
    dest: "{{tmp_dir}}/template.txt"

